# Generated by Django 5.1.6 on 2025-04-20 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repuestos',
            options={'verbose_name': 'Repuesto', 'verbose_name_plural': 'Repuestos'},
        ),
    ]
