# Generated by Django 5.1.6 on 2025-03-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuestos',
            name='nombre',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='repuestos',
            name='numero_factura',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
