# Generated by Django 5.1.6 on 2025-03-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_repuestos_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historialrepuestos',
            table='inventario_historial_repuestos',
        ),
    ]
