# Generated by Django 5.1.6 on 2025-05-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_repuestos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='numero_factura',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
