# Generated by Django 5.1.6 on 2025-03-24 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_historialrepuestos_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('proveedor', models.CharField(max_length=255)),
                ('numero_factura', models.CharField(max_length=100)),
                ('cai', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='repuestos',
            name='numero_factura',
        ),
        migrations.AddField(
            model_name='repuestos',
            name='factura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='inventario.factura'),
            preserve_default=False,
        ),
    ]
