# Generated by Django 5.1.6 on 2025-05-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_factura_numero_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuestos',
            name='repuesto_id_unico',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
