# Generated by Django 5.1.6 on 2025-04-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_factura_created_at_factura_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='codigo',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
