# Generated by Django 5.1.6 on 2025-04-07 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas_buses', '0005_remove_horarioruta_conductor'),
        ('ventas', '0002_factura_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ruta',
        ),
        migrations.AddField(
            model_name='ticket',
            name='horario_ruta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='rutas_buses.horarioruta'),
            preserve_default=False,
        ),
    ]
