# Generated by Django 5.1.6 on 2025-04-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_remove_factura_logo_remove_ticket_ruta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='partida_nacimiento_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='responsable_dpi',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='responsable_menor',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
