# Generated by Django 5.1.6 on 2025-04-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_ticket_partida_nacimiento_id_ticket_responsable_dpi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='precio_con_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
