# Generated by Django 5.1.6 on 2025-04-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_ticket_precio_con_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
