# Generated by Django 5.1.6 on 2025-04-09 23:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas_buses', '0007_remove_ruta_bus_ruta_bus'),
        ('ventas', '0007_factura_updated_at_ticket_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='origen',
            field=models.CharField(choices=[('sistema', 'Sistema'), ('manual', 'Manual')], default='sistema', max_length=10),
        ),
        migrations.CreateModel(
            name='CierreDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, unique=True)),
                ('total_facturas', models.PositiveIntegerField()),
                ('total_monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facturas', models.ManyToManyField(related_name='cierres', to='ventas.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_combustible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uuid_combustible', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('numero_factura', models.CharField(db_index=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combustible', to='rutas_buses.bus')),
            ],
        ),
    ]
