# Generated by Django 5.1.6 on 2025-04-14 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas_buses', '0008_alter_ruta_bus'),
        ('ventas', '0008_factura_monto_factura_origen_cierrediario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combustible',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combustible',
            name='proveedor',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='combustible',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combustible', to='rutas_buses.bus'),
        ),
        migrations.AlterField(
            model_name='combustible',
            name='precio_combustible',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
