# Generated by Django 5.1.6 on 2025-05-07 01:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_combustible_cantidad_combustible_proveedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_gasto', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('numero_factura', models.CharField(db_index=True, max_length=20, unique=True)),
                ('proveedor', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='combustible',
            name='proveedor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
