# Generated by Django 5.1.6 on 2025-05-24 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_gastocompra_alter_combustible_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combustible',
            name='cantidad',
        ),
    ]
