# Generated by Django 5.1.6 on 2025-03-24 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas_buses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioPredefinido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_salida', models.TimeField(unique=True)),
            ],
            options={
                'verbose_name': 'Horario Predefinido',
                'verbose_name_plural': 'Horarios Predefinidos',
                'ordering': ['hora_salida'],
            },
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='bus',
        ),
        migrations.AddField(
            model_name='ruta',
            name='numero_ruta',
            field=models.CharField(db_index=True, default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HorarioRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=10)),
                ('hora_salida', models.TimeField()),
                ('hora_llegada', models.TimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='rutas_buses.bus')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='rutas_buses.ruta')),
            ],
            options={
                'unique_together': {('ruta', 'bus', 'dia', 'hora_salida')},
            },
        ),
    ]
