# Generated by Django 5.1.6 on 2025-02-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas_buses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ruta',
            name='horarios',
            field=models.ManyToManyField(related_name='routes', to='rutas_buses.horarios'),
        ),
    ]
