# Generated by Django 5.1.6 on 2025-03-25 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas_buses', '0002_horariopredefinido_remove_ruta_bus_ruta_numero_ruta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioruta',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios', to='rutas_buses.conductor'),
        ),
    ]
