# Generated by Django 5.1.6 on 2025-04-06 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas_buses', '0004_horarioruta_created_at_horarioruta_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarioruta',
            name='conductor',
        ),
    ]
