# Generated by Django 5.1.6 on 2025-04-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas_buses', '0005_remove_horarioruta_conductor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='bus',
            field=models.ManyToManyField(related_name='rutas', to='rutas_buses.bus'),
        ),
    ]
