# Generated by Django 5.1.6 on 2025-04-07 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas_buses', '0006_ruta_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='bus',
        ),
        migrations.AddField(
            model_name='ruta',
            name='bus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='rutas_buses.bus'),
            preserve_default=False,
        ),
    ]
