# Generated by Django 5.1.6 on 2025-04-13 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas_buses', '0007_remove_ruta_bus_ruta_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='rutas_buses.bus'),
        ),
    ]
