# Generated by Django 5.1.6 on 2025-04-20 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas_buses', '0008_alter_ruta_bus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name': 'Bus', 'verbose_name_plural': 'Buses'},
        ),
        migrations.AlterModelOptions(
            name='conductor',
            options={'verbose_name': 'Conductor', 'verbose_name_plural': 'Conductores'},
        ),
    ]
